name: ArchLinux Repo

on:
  schedule:
  - cron: '0 0 * * *'
  push:
    branches: [ master ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update packages
      run: archlinux/sync/ci